name: exercise-check

on:
  push:
    branches: [ Buoi* ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Dependencies
      run: msbuild -t:restore -p:RestorePackagesConfig=true

    - name: Build solution
      run: msbuild /p:Configuration=Debug
