name: stable-check-and-release

on:
  pull_request:
    branches: [ master, DEVELOP ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Dependencies
      run: msbuild -t:restore

    - name: Build solution
      run: msbuild /p:Configuration=Debug
      
    - name: Run merged executable
      run: |
        bin\debug\ConsoleApp1.exe --merge-source
      id: run_executable

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: DEVELOP_${{ github.sha }}
        release_name: DEVELOP_$(date +'%d%m%Y_%H%M')
        draft: false
        prerelease: true

    - name: Upload to GitHub Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin\\Debug\\Program_*.cs
        asset_name: Program_$(date +'%d%m%Y_%H%M').cs
        asset_content_type: text/plain
